#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <model-name>"
    exit 1
fi

echo "Fetching model information..."
model_information=$(firectl -a zeddev get model $1 -o json)

model_name=$(echo ${model_information} | jq --raw-output --join-output '.deployed_model_refs.[0].name')
deployment=$(echo ${model_information} | jq --raw-output --join-output '.deployed_model_refs.[0].deployment')
deployment_id=$(echo $deployment | awk -F'/' '{print $NF}')

echo "Fetching deployment information..."
deployment_information=$(firectl -a zeddev get deployment ${deployment_id} -o json)

deployment_route_handle=$(echo ${deployment_information} | jq --raw-output --join-output '.direct_route_handle')
direct_route="https://${deployment_route_handle}/v1"

echo ""
echo "Model Name: $model_name"
echo "Deployment: $deployment"

echo "Deployment ID: $deployment_id"
echo "Direct Route: $direct_route"

echo ""
echo "Data to put into Kubernetes secret:"

echo "model: $(echo -n ${model_name} | base64)"
echo "api_url: $(echo -n ${direct_route} | base64)"
