#!/usr/bin/env bash

find train -name "*.md" | sed 's/.*\/\([0-9]*\)\.md/\1/' | sort -n | awk 'BEGIN {last=0} {if ($1 != last+1) {for (i=last+1; i<$1; i++) print "Missing: " i}; last=$1} END {print "Highest: " last}'
